maxThreads: 8
maxJobs: 50
execPath: '/DCEG/Projects/Exome/SequencingData/GATK_binaries/gatk-4.0.11.0/'
outPath: '/home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/output/'
workingPath: '/home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/'
sampleFile: '/DCEG/CGF/Bioinformatics/Production/Bari/Sentieon_germline_pipeline/example_runs/example_bams.list'
  # FOR germline_from_bam:
    # sample /path/to/file.bam
queue: 'seq-calling*.q'
logDir: '/home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/output/logs'
snakePath: '/home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/scripts/'

# bed: '///.bed'

# hg19
# refGenome: '/CGF/Resources/Data/genome/hg19_canonical_correct_chr_order.fa'


