maxThreads: 8
maxJobs: 50
gatkPath: '/DCEG/Projects/Exome/SequencingData/GATK_binaries/gatk-4.0.11.0/gatk-package-4.0.11.0-local.jar'
inputDir: '/Volumes/ifs/DCEG/Home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/example_data/bam'
outputDir: '/home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/output/'
tempDir: '/home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/'
intervalFile: '/DCEG/Projects/Exome/SequencingData/variant_scripts_V3_in_process/variant_intervals_beds/variant_calling_intervals_120430_HG19_ExomeV3_UTR_merged_padded250bp_merged_4000parts/120430_HG19_ExomeV3_UTR_merged_padded250bp_merged.intervals'
queue: 'seq-calling*.q'
logDir: '/home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/output/logs'
snakePath: '/home/sumans/Project_Git_Repos/variantCallingPipelineGermlineHC4/scripts/'

# bed: '///.bed'

# hg19
refGenome: '/CGF/Resources/Data/genome/hg19_canonical_correct_chr_order.fa'


