maxThreads: 20
maxJobs: 100

inputDir: '/DCEG/CGF/Bioinformatics/Production/Shalabh/variantCallingPipelineGermlineHC4/example_data/bam/'
outputDir: '/DCEG/CGF/Bioinformatics/Production/Shalabh/variantCallingPipelineGermlineHC4/output_ScatterGather_3/'
logDir: '/DCEG/CGF/Bioinformatics/Production/Shalabh/variantCallingPipelineGermlineHC4/output_ScatterGather_3/logs'
tempDir: '/ttemp/'

intervalFile: '/DCEG/Projects/Exome/SequencingData/variant_scripts_V3_in_process/variant_intervals_beds/variant_calling_intervals_120430_HG19_ExomeV3_UTR_merged_padded250bp_merged_4000parts/120430_HG19_ExomeV3_UTR_merged_padded250bp_merged.intervals'

queue: 'xlong.q'
snakePath: '/DCEG/CGF/Bioinformatics/Production/Shalabh/variantCallingPipelineGermlineHC4/scripts/'

gatkPath: '/DCEG/Projects/Exome/SequencingData/GATK_binaries/gatk-4.0.11.0/gatk-package-4.0.11.0-local.jar'
# bed: '///.bed'

# hg19
refGenome: '/CGF/Resources/Data/genome/hg19_canonical_correct_chr_order.fa'
dictionaryFile: '/DCEG/Resources/Data/genome/hg19_canonical_correct_chr_order.dict'


